apiVersion: apps/v1
kind: Deployment
metadata:
  name: makerspacebonn-discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makerspacebonn-discord-bot
  template:
    metadata:
      labels:
        app: makerspacebonn-discord-bot
    spec:
      containers:
        - name: makerspacebonn-discord-bot
          image: ghcr.io/agiledivider/msb-bot:f9bce6875720cbf83ba0bbcc1b5fe4d5b19f1394
          env:
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: DISCORD_TOKEN