apiVersion: apps/v1
kind: Deployment
metadata:
  name: makerspacebonn-discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makerspacebonn-discord-bot
  template:
    metadata:
      labels:
        app: makerspacebonn-discord-bot
    spec:
      containers:
        - name: makerspacebonn-discord-bot
          image: ghcr.io/lxfrdl/msb-bot:1d9d9f5083e1600f82a61038652078ef99884caf
          env:
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: DISCORD_TOKEN