name: release dockerimage and update kubernetes manifests

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Execute tests
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache-new \
            -t ghcr.io/${{ github.repository_owner }}/msb-bot:latest \
            -t ghcr.io/${{ github.repository_owner }}/msb-bot:${{ github.sha }} \
            --push .
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Update Kubernetes Manifests
        run: |
          sed -i 's|image: ghcr.io/.*/msb-bot:.*|image: ghcr.io/${{ github.repository_owner }}/msb-bot:${{ github.sha }}|' k8s/deployment.yaml
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add k8s/deployment.yaml
          git commit -m "chore: update Kubernetes manifests with image tag ${{ github.sha }}"
          git push